import { Roboto, Roboto_Condensed } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  variable: "--font-Roboto",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const roboto_condensed = Roboto_Condensed({
  variable: "--font-Roboto_Condensed",
  subsets: ["latin"],
});

export const metadata = {
  title: "Car Farm Social",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/favicon-96x96.png", sizes: "96x96" },
      { url: "/favicon.svg", type: "image/svg+xml" },
      { url: "/favicon.ico", type: "image/x-icon" },
    ],
    shortcut: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
  manifest: "/site.webmanifest",
  appleWebApp: {
    title: "My WebSite",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${roboto_condensed.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
