import { Roboto } from "next/font/google";
import "./globals.css";


const roboto = Roboto({
  variable: "--font-Roboto",
  subsets: ["latin"],
});

export const metadata = {
  title: "Car Farm Social",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>{children}</body>
    </html>
  );
}
