import { Roboto, Roboto_Condensed } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  variable: "--font-Roboto",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const roboto_condensed = Roboto_Condensed({
  variable: "--font-Roboto_Condensed",
  subsets: ["latin"],
});

export const metadata = {
  title: "Car Farm Social",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${roboto_condensed.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
